#   application.properties - App Settings File

# server
server.port=8080

#Application name
spring.application.name=AI_Secure_Data_Intelligence_Platform

# mongodb
spring.config.import=optional:file:.env[.properties]
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/secureai_db}
spring.data.mongodb.database=secureai_db

# upload
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
spring.servlet.multipart.enabled=true

# logging
logging.level.root=INFO
logging.level.com.secureai=DEBUG
logging.level.org.springframework.data.mongodb=INFO

# json
spring.jackson.default-property-inclusion=non_null

# Format dates as readable strings instead of numbers
spring.jackson.serialization.write-dates-as-timestamps=false

# error
server.error.include-message=always
server.error.include-binding-errors=always